{{- if and .Values.installApps .Values.applications.icebergCatalog.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceberg-catalog
  namespace: {{ .Values.argocdNamespace | default "argocd" }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.project | default "lakehouse" }}
  
  source:
    repoURL: {{ .Values.repoURL | required "repoURL is required" }}
    targetRevision: {{ .Values.targetRevision | default "HEAD" }}
    path: platform/iceberg-catalog
    helm:
      valueFiles:
        - values.yaml
        - ../../env/{{ .Values.environment }}/iceberg-catalog-values.yaml
  
  destination:
    server: {{ .Values.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.platformNamespace | default "lakehouse-platform" }}
  
  syncPolicy:
    automated:
      prune: {{ .Values.applications.icebergCatalog.syncPolicy.prune | default true }}
      selfHeal: {{ .Values.applications.icebergCatalog.syncPolicy.selfHeal | default true }}
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  

  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
{{- end }}
