{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sample-service.fullname" . }}
  labels:
    {{- include "sample-service.labels" . | nindent 4 }}
    prometheus: lakehouse
spec:
  selector:
    matchLabels:
      {{- include "sample-service.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
